CREATE DATABASE FRPS_CREDIT_CARDS;
CREATE DATABASE FRPS_CREDIT_CARDS;

CREATE TABLE FRPS_CREDIT_CARDS.CREDIT_CARDS(
id INT NOT NULL AUTO_INCREMENT,
cardnumber VARCHAR(255) NOT NULL,
expiration VARCHAR(255) NOT NULL,
user_id INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE FRPS_USERS.USER(
id INT NOT NULL AUTO_INCREMENT,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
image LONGBLOB NOT NULL,
phone VARCHAR(255) NOT NULL,
gender VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
pan_number VARCHAR(255) NOT NULL ,
PRIMARY KEY (id)
);